image:
  file: .gitpod.Dockerfile

tasks:
  - init: psql --command "CREATE USER postgres WITH SUPERUSER PASSWORD 'postgres';"
  - command: psql --command "CREATE USER postgres WITH SUPERUSER PASSWORD 'postgres';" && mix ecto.create && mix ecto.migrate

vscode:
  extensions:
    - JakeBecker.elixir-ls@0.2.25:X1tqg5Hmluq055QJpf0/7A==
    - mjmcloug.vscode-elixir@1.1.0:w8GjsJyyhVFmCZmBc2Ws7A==
